dist: bionic

sudo: false

language: cpp

compiler: gcc

addons:
    apt:
        sources:
            - sourceline: 'ppa:mhier/libboost-latest'
        packages:
            - cmake
            - lcov
            - cppcheck
            - libboost1.67-dev

before_script:
    - ./travis/before_script.sh

script:
    - ./travis/script.sh

after_script:
    - ./travis/after_script.sh
